### ISSUE TITLE
Truncating text for a manageable layout

### ISSUE THREAD

**Issue by sgoshorn** [CCALI/caw#29]
Currently text displayed in lists is not truncated so lists or selections or drag/drop items can be unwieldy. Switch to a single or double line fixed height, maybe with hover expander to show all the text. This would make lists are easier to scan and scroll and drag/drop items would be easier to operate.

**Comment by emasters** [comment]
@sgoshorn it looks like this is being aggravated by the presence of HTML in the questions, especially `<p>` tags. If possible we should either not store the HTML or at least strip it when displaying text fields in QW.

**Comment by sgoshorn** [comment]
We should keep the HTML markup including paragraphs and lists. Authors will likely find those useful. I think some CSS markup might be enough to chop off the text, using something like the CSS overflow/max-height properties. Otherwise doing a direct string truncate during display would be the next step.

**Comment by emasters** [comment]
OK. The presence of `<p>` tags is what's mostly causing the the check box to appear a line above because the tag is breaking the layout. The top question is newer after CKeditor and HTML handling was put into place, The bottom 2 questions are older, pre-markup. The differnce is the presence of the `<p>` tag in the top question.

![qwlayoutbreakage20170628](https://user-images.githubusercontent.com/741239/27654601-912f243e-5c10-11e7-9251-ff4f07bc8c42.PNG)

**Comment by sgoshorn** [comment]
Sounds like an HTML strip function along with a character limit (ellipsis) would fix this and the display in the table as well.

**Comment by sgoshorn** [comment]
Fixed using string truncation.
