### ISSUE TITLE
QuizWright quizzes should display a different color in the Viewer - suggest green

### ISSUE THREAD

**Issue by johnmayer** [CCALI/caw#78]
When you run a CALI lesson you see the blue viewer. When you run a QuizWright Quiz, you should see a different color - like light green.  

BTW, Autopublish lessons should be a different color as well. 

.....and the logo in the top, left, should be different for all three too.

**Comment by sgoshorn** [comment]
AP lessons have a landing page distinct from regular lessons which has the change for AP logo and other AP bits. (They share identical versions of the viewer JS and CSS.) The viewer handles AP and QW lessons identically since there's no QW detection happening. If detection is added we could things like: change logo, make score more prominent, turn off navigation.

**Comment by sgoshorn** [comment]
Style sheet could be changed too to get different colors.

**Comment by sgoshorn** [comment]
QuizWright logo added. Using the <GENERATOR> tag. If present and QW, switch from AP or Lesson logo to QW logo.

**Comment by sgoshorn** [comment]
We settled on Self-Published vs CALI icons.
