### ISSUE TITLE
When I go to www.cali.org/quizright, I have to login even if I am already logged in to CALI website

### ISSUE THREAD

**Issue by johnmayer** [CCALI/caw#79]
When I go to www.cali.org/quizright, I have to login even if I am already logged in to CALI website. 

Why can't QuizWright know that I am already logged in?

**Comment by sgoshorn** [comment]
Review A2J Author's Drupal login for the authoring app.

**Comment by emasters** [comment]
@sgoshorn any progress to report on this?

**Comment by emasters** [comment]
@sgoshorn I should mention that any work on a single sign on solution needs be done in `https://github.com/CCALI/caw/blob/quizwright/master/includes/drupal_user.php` so that the main code for the app remains neutral about user management. This is key so that we don't need to make core changes when we switch to LDAP for authentication

**Comment by emasters** [comment]
@sgoshorn path forward on QW/Drupal authentication:
 * pass `session_id()` through dashboard menu link to QW
 * use the `session_id` to get the `uid` from the `sessions` table in Drupal
 * use the `uid` to get `name` and `password` from Drupal
 * check the QW `people` table for the `username` and `password`
 * if it's there, login
 * if not there create a new user and login.
Working on this locally today. Most likely have code on d7dev tomorrow.
